import { Dimensions, StyleSheet } from 'react-native';
import { BG, BLUE, BLUE2, CARD, MUTED, RED, SOFT, SOFT2, TEXT } from './colors';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: BG },
  page: { flex: 1, backgroundColor: BG, paddingHorizontal: 20 },
  bottomPad: { paddingBottom: 120 },
  loginWrap: { minHeight: '100%', justifyContent: 'center', padding: 22 },
  logoWrap: { alignItems: 'center', marginBottom: 42 },
  logoCircle: { width: 74, height: 74, borderRadius: 37, backgroundColor: BLUE, alignItems: 'center', justifyContent: 'center' },
  logoText: { fontSize: 28, color: BLUE, fontWeight: '900', marginTop: 14 },
  tagline: { color: MUTED, fontSize: 14 },
  loginCard: { backgroundColor: CARD, borderRadius: 12, padding: 30 },
  h1: { fontSize: 26, fontWeight: '900', color: TEXT },
  copy: { color: MUTED, fontSize: 15, lineHeight: 22, marginVertical: 8 },
  label: { fontSize: 12, color: '#646A77', fontWeight: '900', letterSpacing: 1.2, textTransform: 'uppercase', marginTop: 18, marginBottom: 8 },
  inputBox: { height: 58, borderRadius: 8, backgroundColor: '#F0EFF9', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, gap: 12 },
  input: { flex: 1, fontSize: 16, color: TEXT },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  forgot: { color: BLUE, fontWeight: '800', fontSize: 12 },
  primaryBtn: { height: 62, borderRadius: 31, backgroundColor: BLUE, alignItems: 'center', justifyContent: 'center', marginTop: 32, marginBottom: 24 },
  primaryText: { color: 'white', fontSize: 16, fontWeight: '900' },
  centerText: { textAlign: 'center', color: '#565C69' },
  link: { color: BLUE, fontWeight: '900' },
  topHeader: { height: 58, flexDirection: 'row', alignItems: 'center', gap: 18 },
  brandSmall: { flex: 1, color: BLUE, fontSize: 18, fontWeight: '900' },
  smallAvatar: { width: 40, height: 40, borderRadius: 20, borderWidth: 3, borderColor: BLUE, alignItems: 'center', justifyContent: 'center' },
  screenTitle: { fontSize: 30, fontWeight: '900', color: TEXT, marginTop: 10 },
  bigTitle: { fontSize: 33, fontWeight: '900', color: TEXT, marginTop: 28 },
  subTitle: { fontSize: 15, color: '#69707C' },
  lastUpdated: { color: BLUE, fontSize: 13, textAlign: 'right', fontWeight: '900', letterSpacing: 1 },
  statusCard: { backgroundColor: CARD, borderRadius: 24, padding: 28, marginTop: 24 },
  ring: { width: 178, height: 178, borderRadius: 89, borderWidth: 12, borderColor: BLUE, borderLeftColor: '#E7E7F2', alignSelf: 'center', alignItems: 'center', justifyContent: 'center' },
  ringMain: { fontSize: 34, fontWeight: '900', color: BLUE },
  ringSub: { fontSize: 12, fontWeight: '900', letterSpacing: 2, color: '#777C88' },
  sectionTitle: { fontSize: 18, fontWeight: '900', color: TEXT, marginVertical: 10 },
  body: { color: '#656B78', fontSize: 15, lineHeight: 23 },
  pillRow: { flexDirection: 'row', gap: 10, flexWrap: 'wrap', marginTop: 8 },
  smallPill: { backgroundColor: '#E6F2FF', borderRadius: 18, paddingHorizontal: 12, paddingVertical: 7, flexDirection: 'row', alignItems: 'center', gap: 6, alignSelf: 'flex-start' },
  grayPill: { backgroundColor: '#EFEFF7' },
  smallPillText: { fontSize: 11, color: BLUE2, fontWeight: '900' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, marginTop: 28 },
  metricCard: { width: (width - 56) / 2, backgroundColor: SOFT, borderRadius: 20, padding: 20, minHeight: 148 },
  metricTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  roundIcon: { width: 46, height: 46, borderRadius: 23, backgroundColor: 'white', alignItems: 'center', justifyContent: 'center' },
  statusTag: { fontSize: 10, color: BLUE, fontWeight: '900', backgroundColor: '#E6F2FF', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5, alignSelf: 'flex-start' },
  metricNum: { fontSize: 30, fontWeight: '900', color: TEXT, marginTop: 18 },
  metricLabel: { fontSize: 12, color: MUTED, fontWeight: '800', letterSpacing: 1 },
  trendCard: { backgroundColor: SOFT, borderRadius: 24, padding: 22, marginTop: 28 },
  bars: { height: 178, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'center', gap: 12, marginTop: 12 },
  bar: { width: 34, borderTopLeftRadius: 8, borderTopRightRadius: 8 },
  times: { fontSize: 10, color: '#7D8290', letterSpacing: 1, fontWeight: '700', marginTop: 12 },
  tabBar: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 82, backgroundColor: 'white', borderTopLeftRadius: 24, borderTopRightRadius: 24, flexDirection: 'row', justifyContent: 'space-around', paddingTop: 10 },
  tab: { alignItems: 'center', justifyContent: 'center', borderRadius: 14, paddingHorizontal: 10, minWidth: 58, height: 55 },
  tabActive: { backgroundColor: '#E9F2FF' },
  tabText: { fontSize: 9, color: '#747B89', fontWeight: '900', marginTop: 4 },
  tabTextActive: { color: BLUE },
  stitch: { backgroundColor: 'rgba(0,0,0,0.36)', color: 'white', fontSize: 11, textAlign: 'center', padding: 7, marginHorizontal: -20 },
  mapScreen: { flex: 1, backgroundColor: '#B7DEC0' },
  mapCanvas: { height: 560, overflow: 'hidden' },
  mapRoad: { position: 'absolute', backgroundColor: 'rgba(255,255,255,0.32)' },
  tinyRed: { position: 'absolute', width: 10, height: 10, borderRadius: 5, backgroundColor: RED, borderWidth: 2, borderColor: '#F7B3B3' },
  mapPin: { position: 'absolute', top: '43%', left: '42%', width: 72, height: 72, borderRadius: 36, borderWidth: 5, borderColor: '#5CA3E7', backgroundColor: 'rgba(255,255,255,0.88)', alignItems: 'center', justifyContent: 'center' },
  pinLabel: { position: 'absolute', bottom: -18, color: BLUE, fontSize: 10, fontWeight: '900', backgroundColor: '#E6F2FF', paddingHorizontal: 8, borderRadius: 4 },
  nearest: { position: 'absolute', top: 78, left: 12, right: 12, height: 58, borderRadius: 30, backgroundColor: BLUE, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 20 },
  nearestTitle: { color: 'white', fontSize: 16, fontWeight: '900', flex: 1 },
  nearestDist: { color: 'white', fontSize: 15 },
  legendCard: { position: 'absolute', top: 390, left: 12, right: 12, backgroundColor: 'white', borderRadius: 10, padding: 22 },
  legendRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginVertical: 8 },
  legendDot: { width: 14, height: 14, borderRadius: 7 },
  legendCount: { marginLeft: 'auto', fontWeight: '900', backgroundColor: '#F2F4FF', borderRadius: 10, paddingHorizontal: 8 },
  liveBox: { backgroundColor: '#F3F1FF', borderRadius: 10, padding: 16, marginTop: 18 },
  micro: { fontSize: 11, color: '#8B909E', letterSpacing: 2, fontWeight: '900' },
  italic: { fontStyle: 'italic', fontWeight: '700', color: TEXT, lineHeight: 20 },
  statsRow: { flexDirection: 'row', gap: 16, marginTop: 24 },
  statBox: { flex: 1, backgroundColor: SOFT, borderRadius: 12, padding: 24, minHeight: 128 },
  statActive: { backgroundColor: '#277CE9' },
  statNumber: { fontSize: 34, color: BLUE, fontWeight: '900', marginTop: 22 },
  chips: { flexDirection: 'row', gap: 10, marginVertical: 24 },
  chip: { backgroundColor: '#E3E5ED', borderRadius: 18, paddingVertical: 10, paddingHorizontal: 18, color: '#666C78', fontWeight: '800' },
  chipActive: { backgroundColor: BLUE, color: 'white' },
  feedCard: { backgroundColor: 'white', borderRadius: 14, padding: 20, marginBottom: 18 },
  reportTop: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
  locationCircle: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#EEF3FF', alignItems: 'center', justifyContent: 'center' },
  reportTitle: { fontSize: 17, fontWeight: '900', color: TEXT },
  reportBy: { fontSize: 12, color: MUTED, marginTop: 2 },
  redTag: { backgroundColor: '#FFE5E9', color: '#C82336', borderRadius: 18, paddingVertical: 8, paddingHorizontal: 11, fontSize: 10, fontWeight: '900', overflow: 'hidden', maxWidth: 88, textAlign: 'center' },
  reportDesc: { color: '#535968', fontSize: 15, lineHeight: 24, marginVertical: 18 },
  plus: { backgroundColor: '#EEF2FF', color: BLUE, fontSize: 11, borderRadius: 9 },
  verify: { backgroundColor: '#F2F5FF', borderRadius: 20, paddingVertical: 10, paddingHorizontal: 16, color: BLUE, fontWeight: '900', overflow: 'hidden' },
  fab: { position: 'absolute', right: 22, bottom: 102, width: 62, height: 62, borderRadius: 31, backgroundColor: BLUE, alignItems: 'center', justifyContent: 'center' },
  alertCard: { backgroundColor: SOFT, borderRadius: 20, padding: 26, marginTop: 22 },
  twoCols: { flexDirection: 'row', gap: 14, marginVertical: 20 },
  tipCard: { flex: 1, backgroundColor: SOFT2, borderRadius: 17, padding: 22, minHeight: 150 },
  statValueDark: { fontSize: 26, fontWeight: '900', color: TEXT },
  timeline: { flexDirection: 'row', marginTop: 18 },
  timelineLine: { position: 'absolute', left: 10, top: 0, bottom: -20, width: 2, backgroundColor: '#DFE2EC' },
  timelineDot: { width: 22, height: 22, borderRadius: 11, borderWidth: 3, borderColor: BLUE, backgroundColor: 'white', marginTop: 20, alignItems: 'center', justifyContent: 'center' },
  timelineCard: { flex: 1, backgroundColor: '#E4E6EF', borderRadius: 16, padding: 22, marginLeft: 22 },
  timelineTitle: { fontSize: 22, color: TEXT, fontWeight: '900' },
  timelineDate: { fontSize: 18, color: '#555B68', fontWeight: '900', textAlign: 'center', marginTop: 22 },
  timelineTime: { color: MUTED, textAlign: 'center', marginBottom: 18 },
  impactHero: { backgroundColor: SOFT, borderRadius: 24, padding: 28, marginTop: 24 },
  massive: { fontSize: 74, color: BLUE, fontWeight: '900' },
  units: { position: 'absolute', right: 24, top: 128, color: MUTED, fontWeight: '800' },
  grayCard: { backgroundColor: '#E1E4EC', borderRadius: 20, padding: 24, marginTop: 20 },
  tagBlue: { alignSelf: 'flex-end', backgroundColor: '#DDEEFF', color: BLUE, fontWeight: '900', fontSize: 11, padding: 8, borderRadius: 12 },
  kg: { fontSize: 18, fontWeight: '900', color: TEXT, marginBottom: 14 },
  note: { backgroundColor: '#F8F6FF', color: MUTED, padding: 14, borderRadius: 8 },
  blueCard: { backgroundColor: BLUE, borderRadius: 20, padding: 28, marginTop: 20 },
  whiteTitle: { color: 'white', fontWeight: '900', fontSize: 18, marginTop: 16 },
  whiteText: { color: 'white', fontWeight: '900', fontSize: 18, marginTop: 10 },
  tagWhite: { position: 'absolute', right: 18, top: 18, color: 'white', backgroundColor: 'rgba(255,255,255,0.25)', padding: 8, borderRadius: 12, fontSize: 11, fontWeight: '900', overflow: 'hidden' },
  trendBlank: { backgroundColor: SOFT, borderRadius: 20, padding: 24, marginTop: 20, minHeight: 250 },
  goal: { position: 'absolute', right: 28, top: 70, color: BLUE, fontWeight: '800' },
  months: { marginTop: 128, color: '#6D7381', fontSize: 11, letterSpacing: 1 },
  listRow: { backgroundColor: 'white', borderRadius: 16, padding: 18, marginTop: 14, flexDirection: 'row', alignItems: 'center', gap: 14 },
  listTitle: { fontSize: 16, fontWeight: '900', color: TEXT },
  listRight: { fontSize: 16, fontWeight: '900', color: TEXT },
  switchOn: { width: 42, height: 24, borderRadius: 12, backgroundColor: BLUE, justifyContent: 'center', alignItems: 'flex-end', padding: 2 },
  knobOn: { width: 20, height: 20, borderRadius: 10, backgroundColor: 'white' },
  switchOff: { width: 42, height: 24, borderRadius: 12, backgroundColor: '#D8DBE4', justifyContent: 'center', alignItems: 'flex-start', padding: 2 },
  knobOff: { width: 20, height: 20, borderRadius: 10, backgroundColor: 'white' },
  profileCard: { backgroundColor: SOFT, borderRadius: 14, padding: 22, flexDirection: 'row', alignItems: 'center', gap: 18, marginVertical: 16 },
  avatar: { width: 84, height: 84, borderRadius: 42, backgroundColor: '#DFF4EE', alignItems: 'center', justifyContent: 'center' },
  profileName: { fontSize: 22, color: TEXT, fontWeight: '900' },
  demoBox: { backgroundColor: '#F3F6FF', borderRadius: 14, padding: 14, marginTop: 14 },
  successMsg: { color: BLUE, fontWeight: '900', marginTop: 16, textAlign: 'center' },
  logoutMini: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#E9F2FF', alignItems: 'center', justifyContent: 'center' },
  logoutBtn: { marginTop: 26, height: 58, borderRadius: 18, backgroundColor: 'white', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 },
  logoutText: { color: RED, fontSize: 16, fontWeight: '900' },

  fakeMapHeader: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 10, backgroundColor: '#B7DEC0' },
  fakeMapTitle: { fontSize: 30, color: TEXT, fontWeight: '900' },
  fakeMapSub: { color: '#4C7158', fontWeight: '800', marginTop: 4 },
  mapCanvasNew: { marginHorizontal: 14, height: 430, borderRadius: 30, backgroundColor: '#A9D8B5', overflow: 'hidden', borderWidth: 4, borderColor: 'rgba(255,255,255,0.45)' },
  mapBlock: { position: 'absolute', borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.28)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.5)' },
  mapRoadWide: { position: 'absolute', height: 34, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.42)' },
  mapPath: { position: 'absolute', left: '28%', top: '37%', width: 150, height: 5, borderRadius: 3, backgroundColor: 'rgba(8,116,222,0.18)', transform: [{ rotate: '24deg' }] },
  mapPathActive: { backgroundColor: BLUE, height: 7 },
  stationPin: { position: 'absolute', width: 58, height: 58, marginLeft: -29, marginTop: -29, borderRadius: 29, borderWidth: 4, backgroundColor: 'white', alignItems: 'center', justifyContent: 'center' },
  stationPinActive: { width: 72, height: 72, borderRadius: 36, marginLeft: -36, marginTop: -36, borderWidth: 6 },
  nearestCard: { marginHorizontal: 20, marginTop: -34, backgroundColor: 'white', borderRadius: 22, padding: 20 },
  nearestCardTitle: { fontSize: 22, color: TEXT, fontWeight: '900', marginTop: 4 },
  qualityBubble: { width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center' },
  qualityBubbleText: { color: 'white', fontWeight: '900', fontSize: 18 },
  mapActions: { flexDirection: 'row', gap: 12, marginTop: 18, flexWrap: 'wrap' },
  actionBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#E9F2FF', borderRadius: 18, paddingVertical: 12, paddingHorizontal: 16 },
  actionBtnActive: { backgroundColor: BLUE },
  actionText: { color: BLUE, fontWeight: '900' },
  actionTextActive: { color: 'white' },
  legendCardNew: { margin: 20, backgroundColor: 'white', borderRadius: 18, padding: 22 },

  adminHero: { backgroundColor: 'white', borderRadius: 24, padding: 22, marginTop: 22 },
  adminHeroTitle: { fontSize: 24, color: TEXT, fontWeight: '900', marginTop: 6 },
  adminProgress: { height: 12, borderRadius: 8, backgroundColor: '#E1E7F4', marginVertical: 18, overflow: 'hidden' },
  adminProgressFill: { height: '100%', borderRadius: 8, backgroundColor: BLUE },
  adminGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, marginTop: 22 },
  adminMetric: { width: (width - 54) / 2, backgroundColor: 'white', borderRadius: 20, padding: 18, minHeight: 138 },
  adminIcon: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' },
  quickRow: { flexDirection: 'row', gap: 12, marginBottom: 18 },
  quickCard: { flex: 1, backgroundColor: 'white', borderRadius: 18, padding: 16, minHeight: 96, justifyContent: 'center' },
  quickTitle: { color: TEXT, fontWeight: '900', marginTop: 10, fontSize: 13 },
  userCard: { backgroundColor: 'white', borderRadius: 18, padding: 16, marginBottom: 14, flexDirection: 'row', alignItems: 'center', gap: 14 },
  userAvatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#E9F2FF', alignItems: 'center', justifyContent: 'center' },
  statusBadge: { backgroundColor: '#F3F6FF', borderRadius: 14, paddingHorizontal: 10, paddingVertical: 7, fontSize: 11, fontWeight: '900', overflow: 'hidden' },
  sensorCard: { backgroundColor: 'white', borderRadius: 18, padding: 16, marginTop: 14, flexDirection: 'row', alignItems: 'center', gap: 14 },
});
